[workspace]
resolver = "2"
members = ["crates/protocol", "crates/cli", "crates/ui", "drivers/mysql", "drivers/postgres"]

[workspace.package]
version = "0.1.3"
edition = "2021"
rust-version = "1.95"
license-file = "LICENSE"
repository = "https://github.com/OtterMind/sqlx"
authors = ["OtterMind"]

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process", "io-util", "io-std", "signal", "time"] }
base64 = "0.22"
hex = "0.4"
sha2 = "0.10"
sqlx-protocol = { path = "crates/protocol" }

[profile.release]
lto = "thin"
strip = true
